//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exercise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerID { get; set; }
        public string customerName { get; set; }
        public Nullable<int> customerAge { get; set; }
        public string customerAdress { get; set; }
        public Nullable<int> bookID { get; set; }
        public Nullable<int> branchID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
