//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exercise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int personelID { get; set; }
        public string personelName { get; set; }
        public Nullable<decimal> personelSalary { get; set; }
        public Nullable<int> branchID { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
